let eggInfo = [
  "Eggs are good for your eyes. They contain lutein which prevents cataracts and muscle degeneration.",
  "An egg shell can have as many as 17, 000 pores.",
  "Egg shell and yolk color can vary but have no effect on taste or quality.",
  "Breed determines egg shell color. Commercial eggs are brown or white, but some breeds can also lay blue, green, or pink eggs.",
  "Egg yolks are one of the few foods that naturally contain Vitamin D.",
  "Brown eggs are more expensive because the hens that lay them are larger and require more feed.",
  "Duck eggs are higher in fat and better for baking.",
  "Eggs are rich in choline which promotes normal cell activity.",
  "To tell the difference between a raw egg and a hard cooked one, spin it. Hard cooked eggs spin easily, raw eggs wobble.",
  "If you drop an egg on the floor, sprinkle it heavily with salt for easy clean up.",
  "Eggs age more in one day at room temperature than in one week in the refrigerator.",
  "An average hen lays 300 to 325 eggs per year.",
  "It takes a chicken 24 to 26 hours to produce an egg.",
  "As hens age, their eggs become larger.",
  "The fastest omelet maker in the world made 427 two - egg omelets in 30 minutes.",
  "A hen turns her egg nearly 50 times a day to keep the yolk from sticking to the side.",
  "Kiwis lay the largest eggs in relation to their body size of any species of bird.",
  "The word “yolk” derives from an Old English word for “yellow”. Therefore, it is egg white and egg yellow.",
  "Harriet, a hen from the United Kingdom, laid the world’s largest egg in 2010. Her astonishing egg measured 9.1 inches in diameter.",
  "In the studie that the creator of this app did, the most common time for boiling the perfect is 5-6 minutes.",
  "In the studie that the creator of this app did, 61 procent of the people who answered said that they often boils egg.",
];
